#define PMB_NO 3

#define CAN_HEARTBEAT_INTERVAL 500
#define CAN_STATUS_INTERVAL 1000
#define PRINT_INTERVAL 1000
#define OLED_INTERVAL 500
#define CURR_INTERVAL 10
#define VOLT_INTERVAL 20
#define TEMP_INTERVAL 1000
#define UPDATE_INTERVAL 50

#define PRESSURE_INTERVAL 1000

#if (PMB_NO % 2 == 1)
#define PMB_HEARTBEAT_ID 7
#define CAN_BATT_STAT_ID 23
#define CAN_PMB_STAT_ID 24
#else
#define PMB_HEARTBEAT_ID 8
#define CAN_BATT_STAT_ID 25
#define CAN_PMB_STAT_ID 26
#endif

#define CAN_CS_PIN 8
#define MAX_CURR 80
#define SHUNT_RES 1 //mOhm
#define ARR_SIZE 10

//GPIO CONNECTIONS
#define PORT_PMOS GPIOC
#define PIN_PMOS GPIO_PIN_3 //Base_VehPwr

#define PORT_OLED_RESET GPIOC
#define PIN_OLED_RESET GPIO_PIN_4 //OLED_Reset

#define PORT_OFF GPIOC
#define PIN_OFF GPIO_PIN_7 //ReedOff

#define PORT_RELAY GPIOC
#define PIN_RELAY GPIO_PIN_1 //Gate_PMBPwr

#define PORT_ALERT1 GPIOB
#define PIN_ALERT1 GPIO_PIN_13 //BAT_ALERT1

#define PORT_ALERT2 GPIOB
#define PIN_ALERT2 GPIO_PIN_12 //BAT_ALERT2

#define PORT_ERROR GPIOB
#define PIN_ERROR GPIO_PIN_14 //error

#define MAX_CAPACITY 4290000000 //3600000000; // 10000 * 60 * 60 * 100 (scaling fact) (max of 2^32

//PMB 2 - 2755080000
//PMB 3 - 2718360000

//EEPROM CONSTANTS  
#define ADDR_CAPACITY 0
#define ADDR_VOLTAGE 4
#define VOLTAGE_DIFF 20 //200mV difference

//BATT_STATES
#define BATT_DISCHARGING 0
#define BATT_CHARGING 1
#define BATT_FULL 2

//TEMP_SENSOR
#define ADDR_TEMP_SENS 0X4E
#define CONFIG_TEMP_SENS 96

//PRESSURE_SENSOR
#define INTPRES_REF	5
